services:
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: dev
      args:
        APP: server
    environment:
      CORS_ORIGINS: http://localhost:8233
      KEYS_PATH: /go/root/apps/server/keys.example.json
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ./apps:/go/root/apps
