services:
  golang:
    build:
      context: .
      dockerfile: ./apps/golang/Dockerfile
      target: dev
      args:
        APP: golang
    environment:
      CORS_ORIGINS: http://localhost:8233
      KEYS_PATH: /go/root/apps/golang/keys.example.json
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ./apps:/go/root/apps
