services:
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: dev
      args:
        APP: server
    environment: {}
    ports:
      - 9000:3000
    restart: on-failure
    volumes:
      - ./apps:/go/root/apps
