{{- if .Values.keys.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal-codec-server.fullname" . }}
  labels:
    {{- include "temporal-codec-server.labels" . | nindent 4 }}
data:
  encryption-keys: {{ .Values.keys.encryptionKeys | toJson | b64enc | quote }}
{{- end }}
